# Generated by Django 2.1.5 on 2019-02-05 01:48

import bitbank.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='登録メールアドレス')),
                ('email_for_notice', models.EmailField(default='', max_length=254, verbose_name='通知用メールアドレス')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='名前')),
                ('api_key', models.CharField(default='', max_length=255, verbose_name='API KEY')),
                ('api_secret_key', models.CharField(default='', max_length=255, verbose_name='API SECRET KEY')),
                ('notify_if_filled', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='OFF', max_length=10, verbose_name='約定通知')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', bitbank.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(default='btc_jpy', max_length=50, verbose_name='通貨')),
                ('threshold', models.FloatField(verbose_name='到達金額')),
                ('over_or_under', models.CharField(max_length=50, verbose_name='上下')),
                ('alerted_at', models.DateTimeField(null=True, verbose_name='通知日時')),
                ('is_active', models.BooleanField(null=True, verbose_name='有効')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=50, verbose_name='通貨')),
                ('special_order', models.CharField(max_length=50, verbose_name='特殊注文')),
                ('side', models.CharField(max_length=50, verbose_name='買い/売り')),
                ('order_type', models.CharField(max_length=50, verbose_name='注文方法')),
                ('price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='注文価格')),
                ('price_for_stop', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ストップ価格')),
                ('start_amount', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='注文数量')),
                ('remaining_amount', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='未約定数量')),
                ('executed_amount', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='約定済数量')),
                ('average_price', models.FloatField(null=True, verbose_name='約定平均価格')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='注文ステータス')),
                ('order_id', models.CharField(max_length=50, null=True, verbose_name='取引ID')),
                ('ordered_at', unixtimestampfield.fields.UnixTimeStampField(null=True, verbose_name='注文時刻unixtime')),
                ('udpated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cancel_if_done', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bitbank.Order')),
                ('order_if_done', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitbank.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
