# Generated by Django 2.1.5 on 2019-02-03 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_for_stop_limit',
        ),
        migrations.AddField(
            model_name='order',
            name='price_for_stop',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ストップ価格'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alerted_at',
            field=models.DateTimeField(null=True, verbose_name='通知日時'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='over_or_under',
            field=models.CharField(max_length=50, verbose_name='上下'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='pair',
            field=models.CharField(default='btc_jpy', max_length=50, verbose_name='通貨'),
        ),
        migrations.AlterField(
            model_name='order',
            name='average_price',
            field=models.FloatField(null=True, verbose_name='約定平均価格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='executed_amount',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='約定済数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=50, null=True, verbose_name='取引ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(max_length=50, verbose_name='注文方法'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pair',
            field=models.CharField(max_length=50, verbose_name='通貨'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='注文価格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_amount',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='未約定数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(max_length=50, verbose_name='買い/売り'),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_order',
            field=models.CharField(max_length=50, verbose_name='特殊注文'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='注文ステータス'),
        ),
    ]
