# Generated by Django 2.1.5 on 2019-02-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='udpated_at',
            new_name='updated_at',
        ),
    ]
