# Generated by Django 2.1.5 on 2019-02-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_alert',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=10, verbose_name='アラートメール通知'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify_if_filled',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=10, verbose_name='約定通知'),
        ),
    ]
