# Generated by Django 2.1.5 on 2019-01-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.TextField(default='', max_length=255, verbose_name='api_key'),
        ),
        migrations.AddField(
            model_name='user',
            name='api_secret_key',
            field=models.TextField(default='', max_length=255, verbose_name='api_secret_key'),
        ),
    ]
