# Generated by Django 2.1.5 on 2019-02-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_placed',
            new_name='placed_at',
        ),
        migrations.RemoveField(
            model_name='bitbankorder',
            name='cancel_if_done',
        ),
        migrations.RemoveField(
            model_name='bitbankorder',
            name='order_if_done',
        ),
        migrations.AddField(
            model_name='bitbankorder',
            name='pair',
            field=models.CharField(default=1, max_length=50, verbose_name='通貨'),
            preserve_default=False,
        ),
    ]
