# Generated by Django 2.1.5 on 2019-01-27 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expect_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='予想'),
        ),
        migrations.AlterField(
            model_name='order',
            name='limit_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='逆指値価格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='注文価格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_threshold_1',
            field=models.FloatField(blank=True, null=True, verbose_name='①価格到達通知設定'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_threshold_2',
            field=models.FloatField(blank=True, null=True, verbose_name='②価格到達通知設定'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_threshold_3',
            field=models.FloatField(blank=True, null=True, verbose_name='③価格到達通知設定'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_threshold_4',
            field=models.FloatField(blank=True, null=True, verbose_name='④価格到達通知設定'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_threshold_5',
            field=models.FloatField(blank=True, null=True, verbose_name='⑤価格到達通知設定'),
        ),
    ]
