# Generated by Django 2.1.5 on 2019-01-31 05:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0002_auto_20190130_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(choices=[('btc_jpy', 'btc_jpy'), ('xrp_jpy', 'xrp_jpy'), ('ltc_btc', 'ltc_btc'), ('eth_btc', 'eth_btc'), ('mona_jpy', 'mona_jpy'), ('mona_btc', 'mona_btc'), ('bcc_jpy', 'bcc_jpy'), ('bcc_btc', 'bcc_btc')], default='btc_jpy', max_length=50, verbose_name='通貨')),
                ('threshold', models.FloatField(verbose_name='到達金額')),
                ('over_or_below', models.CharField(choices=[('over', 'を超えたら'), ('below', 'を下回ったら')], max_length=50, verbose_name='上下')),
                ('alerted_at', models.DateTimeField(blank=True, verbose_name='通知日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='limit_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notify_if_reach',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_threshold_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_threshold_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_threshold_3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_threshold_4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_threshold_5',
        ),
        migrations.AddField(
            model_name='order',
            name='price_for_stop_limit',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='逆指値の指値'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(verbose_name='注文日時'),
        ),
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('buy', '買い'), ('sell', '売り')], default='SELL', max_length=50, verbose_name='買い/売り'),
        ),
    ]
