# Generated by Django 2.1.5 on 2019-02-12 03:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0002_auto_20190209_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='average_price',
            field=models.FloatField(blank=True, null=True, verbose_name='約定平均価格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_if_done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bitbank.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='executed_amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='約定済数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='取引ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_if_done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitbank.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=unixtimestampfield.fields.UnixTimeStampField(blank=True, null=True, verbose_name='注文時刻unixtime'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='注文価格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_for_stop',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ストップ価格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='未約定数量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='API KEY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_secret_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='API SECRET KEY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_for_notice',
            field=models.EmailField(blank=True, max_length=254, verbose_name='通知用メールアドレス'),
        ),
    ]
