# Generated by Django 2.1.5 on 2019-02-03 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0002_auto_20190203_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_if_done',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bitbank.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_if_done',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bitbank.Order'),
        ),
    ]
