# Generated by Django 2.1.5 on 2019-01-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0002_auto_20190120_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_for_notice',
            field=models.EmailField(default='', max_length=254, verbose_name='通知用メールアドレス'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.TextField(default='', max_length=255, verbose_name='API KEY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_secret_key',
            field=models.TextField(default='', max_length=255, verbose_name='API SECRET KEY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='登録メールアドレス'),
        ),
    ]
