# Generated by Django 2.1.5 on 2019-01-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0003_auto_20190131_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alerted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='通知日時'),
        ),
    ]
