# Generated by Django 2.1.5 on 2019-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0003_auto_20190120_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(default='', max_length=255, verbose_name='API KEY'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_secret_key',
            field=models.CharField(default='', max_length=255, verbose_name='API SECRET KEY'),
        ),
    ]
