# Generated by Django 2.1.5 on 2019-02-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0003_bitbankorder_error_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderRelation',
        ),
    ]
