# Generated by Django 2.1.5 on 2019-03-03 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0003_auto_20190227_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='アップロード日時'),
            preserve_default=False,
        ),
    ]
