# Generated by Django 2.1.5 on 2019-02-14 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0003_auto_20190212_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文', 'verbose_name_plural': '注文'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザ', 'verbose_name_plural': 'ユーザ'},
        ),
        migrations.AddField(
            model_name='user',
            name='remaining_days',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='残日数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='管理者'),
        ),
    ]
