# Generated by Django 2.1.5 on 2019-01-26 01:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0004_auto_20190124_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC_JPY', 'BTC/JPY'), ('XRP_JPY', 'XRP/JPY'), ('LTC_BTC', 'LTC/BTC'), ('ETH_BTC', 'ETH/BTC'), ('MONA_JPY', 'MONA/JPY'), ('MONA_BTC', 'MONA/BTC'), ('BCC_JPY', 'BCC/JPY'), ('BCC_BTC', 'BCC/BTC')], max_length=50, verbose_name='通貨')),
                ('special_order', models.CharField(choices=[('SINGLE', 'SINGLE'), ('IFD', 'IFD'), ('OCO', 'OCO'), ('IFDOCO', 'IFDOCO')], max_length=50, verbose_name='特殊注文')),
                ('buy_sell', models.CharField(choices=[('BUY', '買い'), ('SELL', '売り')], max_length=50, verbose_name='買い/売り')),
                ('order_type', models.CharField(choices=[('NARI', '成行'), ('SASHI', '指値'), ('R_SASHI', '逆指値'), ('STOP_L', 'ストップリミット')], max_length=50, verbose_name='注文方法')),
                ('price', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='注文価格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
