# Generated by Django 2.1.5 on 2019-02-17 07:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0004_auto_20190214_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='件名')),
                ('body', models.CharField(max_length=255, verbose_name='内容')),
                ('email_for_reply', models.EmailField(max_length=254, verbose_name='通知用メールアドレス')),
                ('attachment', models.FileField(upload_to='attachments/')),
                ('date_initiated', models.DateTimeField(auto_now_add=True, verbose_name='問い合わせ日')),
            ],
            options={
                'verbose_name': '問い合わせ',
                'verbose_name_plural': '問い合わせ',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='remaining_days',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='残日数'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
