# Generated by Django 2.1.5 on 2019-01-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0004_auto_20190131_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.CharField(default='有効', max_length=50, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='over_or_below',
            field=models.CharField(choices=[('超えたら', 'を超えたら'), ('下回ったら', 'を下回ったら')], max_length=50, verbose_name='上下'),
        ),
    ]
