# Generated by Django 2.1.5 on 2019-02-24 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0005_auto_20190223_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitbankorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderrelation',
            name='order_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_order', to='bitbank.BitbankOrder', verbose_name='新規注文'),
        ),
        migrations.AlterField(
            model_name='orderrelation',
            name='order_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settle_order_1', to='bitbank.BitbankOrder', verbose_name='決済注文1'),
        ),
        migrations.AlterField(
            model_name='orderrelation',
            name='order_3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settle_order_2', to='bitbank.BitbankOrder', verbose_name='決済注文2'),
        ),
    ]
