# Generated by Django 2.1.5 on 2019-02-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0005_auto_20190217_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='attachments/')),
            ],
            options={
                'verbose_name': '添付ファイル',
                'verbose_name_plural': '添付ファイル',
            },
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='attachment',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='解決済'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='attachment_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bitbank.Attachment'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='attachment_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bitbank.Attachment'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='attachment_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bitbank.Attachment'),
        ),
    ]
