# Generated by Django 2.1.5 on 2019-01-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0005_auto_20190131_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='is_active',
            field=models.CharField(blank=True, default='有効', max_length=50, null=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(null=True, verbose_name='注文日時'),
        ),
    ]
