# Generated by Django 2.1.5 on 2019-01-26 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='currency',
            new_name='pair',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='buy_sell',
            new_name='side',
        ),
        migrations.AddField(
            model_name='order',
            name='executed_amount',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='約定済数量'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=50, null=True, verbose_name='取引ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_amount',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='未約定数量'),
        ),
        migrations.AddField(
            model_name='order',
            name='start_amount',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='注文数量'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNFILLED', '注文中'), ('PARTIALLY_FILLED', '注文中(一部約定)'), ('FULLY_FILLED', '約定済み'), ('CANCELED_UNFILLED', '取消済'), ('CANCELED_PARTIALLY_FILLED', '取消済(一部約定)')], max_length=50, null=True, verbose_name='注文ステータス'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='注文価格'),
        ),
    ]
