# Generated by Django 2.1.5 on 2019-01-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0006_auto_20190126_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('成行', '成行'), ('指値', '指値'), ('逆指値', '逆指値'), ('ストップリミット', 'ストップリミット')], max_length=50, verbose_name='注文方法'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pair',
            field=models.CharField(choices=[('BTC/JPY', 'BTC/JPY'), ('XRP/JPY', 'XRP/JPY'), ('LTC/BTC', 'LTC/BTC'), ('ETH/BTC', 'ETH/BTC'), ('MONA/JPY', 'MONA/JPY'), ('MONA/BTC', 'MONA/BTC'), ('BCC/JPY', 'BCC/JPY'), ('BCC/BTC', 'BCC/BTC')], max_length=50, verbose_name='通貨'),
        ),
    ]
