# Generated by Django 2.1.5 on 2019-02-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0006_auto_20190217_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachment',
            new_name='file',
        ),
    ]
