# Generated by Django 2.1.5 on 2019-02-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0007_auto_20190217_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='attachment_1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='添付ファイル1'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='attachment_2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='添付ファイル2'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='attachment_3',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='添付ファイル3'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
