# Generated by Django 2.1.5 on 2019-01-26 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0007_auto_20190126_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='limit_price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='逆指値価格'),
        ),
    ]
