# Generated by Django 2.1.5 on 2019-01-26 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0008_order_limit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expect_price',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='予想'),
        ),
        migrations.AddField(
            model_name='order',
            name='notify_if_filled',
            field=models.BooleanField(default=False, verbose_name='約定通知'),
        ),
        migrations.AddField(
            model_name='order',
            name='notify_if_reach',
            field=models.BooleanField(default=False, verbose_name='価格到達通知'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_threshold_1',
            field=models.FloatField(null=True, verbose_name='①価格到達通知設定'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_threshold_2',
            field=models.FloatField(null=True, verbose_name='②価格到達通知設定'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_threshold_3',
            field=models.FloatField(null=True, verbose_name='③価格到達通知設定'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_threshold_4',
            field=models.FloatField(null=True, verbose_name='④価格到達通知設定'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_threshold_5',
            field=models.FloatField(null=True, verbose_name='⑤価格到達通知設定'),
        ),
    ]
