# Generated by Django 2.1.5 on 2019-01-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitbank', '0009_auto_20190126_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notify_if_filled',
            field=models.BooleanField(choices=[(True, 'ON'), (False, 'OFF')], default=False, max_length=10, verbose_name='約定通知'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notify_if_reach',
            field=models.BooleanField(choices=[(True, 'ON'), (False, 'OFF')], default=False, verbose_name='価格到達通知'),
        ),
    ]
